export enum actionTypes {
  FETCH_DATA = 'fetch/FETCH_DATA',
  FETCH_ERROR = 'fetch/ERROR',
  FETCH_START = 'fetch/FETCH_START',
  SET_LOADER = 'fetch/SET_LOADER',

  TOGGLE_MODAL = 'toggle/TOGGLE_MODAL',
  CLOSE_MODAL = 'toggle/CLOSE_MODAL',
  OPEN_MODAL = 'toggle/OPEN_MODAL',

  SET_QUERY_SEARCH = 'search/SET_QUERY_SEARCH',
  GET_POSTS_BY_QUERY = 'search/GET_POSTS_BY_QUERY',
  SET_ERROR_SEARCH = 'search/SET_ERROR_SEARCH',
  SET_SEARCH_LOADING = 'search/SET_SEARCH_LOADING',
  REMOVE_SEARCH_ERROR = 'search/REMOVE_SEARCH_ERROR',
  REMOVE_SUGGESTIONS_LOADING = 'search/REMOVE_SUGGESTIONS_LOADING',
  REMOVE_SUGGESTIONS = 'search/REMOVE_SUGGESTIONS',
  ADD_TO_SAVED = 'search/ADD_TO_SAVED',
  REMOVE_FROM_SAVED = 'search/REMOVE_FROM_SAVED',

  EDIT_SUGGESTIONS = 'search/EDIT_SUGGESTIONS',
  START_SOCKET_SUBSCRIPTION = 'sub/START_SOCKET_SUBSCRIPTION',
  STOP_SOCKET_SUBSCRIPTION = 'sub/STOP_SOCKET_SUBSCRIPTION',

  START_FETCH_SORT = 'sort/START_FETCH_SORT',
  SET_SORT_DATA = 'sort/SET_SORT_DATA',
  SORT_DATA = 'sort/SORT_DATA',
  SET_SEARCH_QUERY = 'sort/SET_SEARCH_QUERY',
  SET_SORT_KEY = 'sort/SET_SORT_KEY',
  CANCEL_SORT_DATA_FETCH = 'sort/CANCEL_SORT_DATA_FETCH',

  SIGN_IN = 'auth/SIGN_IN',
  SIGN_UP = 'auth/SIGN_UP',
  AUTH_ERROR = 'auth/AUTH_ERROR',
  LOGOUT = 'auth/LOGOUT',
}
